# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd8a2dd93c89e6a21ec4f50d027ed1313af09fffb5b935becb590c38c1a8e00b6fbf02b8127afe0c96dac800bf03cd19a0cf71331adaf12395abf681c7d46172

test:
  secret_key_base: 817241843ae3aa1dd88c76341e86f9cea2b7330b79e66e384fb8bd22b7fad8d0dcc01680679d0ee2aad073de2923a7e22d5dfe4fd881242861ed995e9e7f0e03

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
